---
title: "Mental state"
author: "Clare Horscroft"
date: "06/08/2021"
output: html_document
---

Investigating various mental states in relation to number of children fathered

```{r setup}
library(TwoSampleMR)
```

## Feeling nervous

```{r }
d <- make_dat("ebi-a-GCST006948", "ukb-b-2227")
d_mr<-mr(d)
d_mr
mr_scatter_plot(d_mr,d)
```

```{r }
d <- make_dat("ukb-b-2227", "ebi-a-GCST006948")
d_mr<-mr(d)
d_mr
mr_scatter_plot(d_mr,d)
```

## Nervous feelings

```{r }
d <- make_dat("ukb-b-20544", "ukb-b-2227")
d_mr<-mr(d)
d_mr
mr_scatter_plot(d_mr,d)
```

```{r }
d <- make_dat("ukb-b-2227", "ukb-b-20544")
d_mr<-mr(d)
d_mr
mr_scatter_plot(d_mr,d)
```

## Suffer from 'nerves'

```{r }
d <- make_dat("ukb-b-19957", "ukb-b-2227")
d_mr<-mr(d)
d_mr
mr_scatter_plot(d_mr,d)
```

```{r }
d <- make_dat("ukb-b-2227", "ukb-b-19957")
d_mr<-mr(d)
d_mr
mr_scatter_plot(d_mr,d)
```

## Worrier / anxious feelings 

```{r }
d <- make_dat("ukb-b-6519", "ukb-b-2227")
d_mr<-mr(d)
d_mr
mr_scatter_plot(d_mr,d)
```

```{r }
d <- make_dat("ukb-b-2227", "ukb-b-6519")
d_mr<-mr(d)
d_mr
mr_scatter_plot(d_mr,d)
```

Maybe some evidence of a negative relationship between nerves/worry and the number of children fathered.